# This file was generated by GoReleaser. DO NOT EDIT.
cask "k8sfoams" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "7dd20febe9c77048123910f56774898847f7710c6878074bbedc278abf9e53ce"
      url "https://github.com/adrianhaj/k8s-pod-foamtree-go/releases/download/v#{version}/k8sfoams_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "dfc83aa7fd5c762e00947bc6179e440442b6ad8dc839a747c643c8d8ecd3a24e"
      url "https://github.com/adrianhaj/k8s-pod-foamtree-go/releases/download/v#{version}/k8sfoams_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fe064147c080429e14a166b170c51bc42073b3dbb0dc11e1ab1ddbaeca7aacde"
      url "https://github.com/adrianhaj/k8s-pod-foamtree-go/releases/download/v#{version}/k8sfoams_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "aaab0f56af1b2521993a8a59e1d979d24f7278846585fb5dbe042a462fa6be42"
      url "https://github.com/adrianhaj/k8s-pod-foamtree-go/releases/download/v#{version}/k8sfoams_#{version}_linux_amd64.tar.gz"
    end
  end

  name "k8sfoams"
  desc "Read-only dashboard of Kubernetes CPU and memory requests per node"
  homepage "https://github.com/adrianhaj/k8s-pod-foamtree-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "k8sfoams"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/k8sfoams"]
    end
  end

  # No zap stanza required
end
