# This file was generated by GoReleaser. DO NOT EDIT.
cask "k8sfoams" do
  version "1.1.0"

  on_macos do
    on_arm do
      sha256 "ee0c60ca64649b9cf1d3e925750d5a2ecee2fde019c21ae52a6c1cca82ddb54a"
      url "https://github.com/adrianhaj/k8s-pod-foamtree-go/releases/download/v#{version}/k8sfoams_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f94e5d74444bc212c6beb103b5ccdee0760f3103f297e69d72b54384154150c6"
      url "https://github.com/adrianhaj/k8s-pod-foamtree-go/releases/download/v#{version}/k8sfoams_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f0a617f46b2fb4e38fdf210b3a6f3444701284fec3731f76cad88566ba94f3c1"
      url "https://github.com/adrianhaj/k8s-pod-foamtree-go/releases/download/v#{version}/k8sfoams_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d07305d8a95d9c327427e407943b45f88657506f2b2ac6675083149389fa5f3d"
      url "https://github.com/adrianhaj/k8s-pod-foamtree-go/releases/download/v#{version}/k8sfoams_#{version}_linux_amd64.tar.gz"
    end
  end

  name "k8sfoams"
  desc "Read-only dashboard of Kubernetes CPU and memory requests per node"
  homepage "https://github.com/adrianhaj/k8s-pod-foamtree-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "k8sfoams"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/k8sfoams"]
    end
  end

  # No zap stanza required
end
